### ISSUE TITLE
Well-FED: Prioritised issues

### ISSUE THREAD

**Issue by ndorfin** [Jae-Huh/hear-me-out#8]
Here's a list of issues we could start working on.

- [ ] #3 Redux
- [ ] #4 Basic PWA
- [ ] #5 ServiceWorkers
- [ ] #6 Linting
- [ ] #7 Unit tests

Please re-order them according to your priorities

I'll add more issues soon.

**Comment by jae-huh** [comment]
Hey @ndorfin, I'm happy with the current order so please proceed when available :)
